apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
  storageClassName: nfs
